Update 002-install-chroot

diff --git a/002-install-chroot b/002-install-chroot
--- a/002-install-chroot
+++ b/002-install-chroot
@@ -25,19 +25,42 @@ else
   exit 1
 fi
 
-if [[ -f `pwd`/100-display-manager-and-desktop ]]; then
-  source 100-display-manager-and-desktop
-else
-  echo "missing file: 100-display-manager-and-desktop"
-  exit 1
-fi
+check_script "100-display-manager-and-desktop"
+check_script "110-install-sound"
+check_script "130-install-printers"
+check_script "140-install-samba"
+check_script "200-install-system-tools"
 
-if [[ -f `pwd`/140-install-samba ]]; then
-  source 140-install-samba
-else
-  echo "missing file: 140-install-samba"
-  exit 1
-fi
+
+#if [[ -f `pwd`/100-display-manager-and-desktop ]]; then
+#  source 100-display-manager-and-desktop
+#else
+#  echo "missing file: 100-display-manager-and-desktop"
+#  exit 1
+#fi
+
+#if [[ -f `pwd`/110-install-sound ]]; then
+#  source 110-install-sound
+#else
+#  echo "missing file: 110-install-sound"
+#  exit 1
+#fi
+
+#if [[ -f `pwd`/130-install-printers ]]; then
+#  source 130-install-printers
+#else
+#  echo "missing file: 130-install-printers"
+#  exit 1
+#fi
+
+#if [[ -f `pwd`/140-install-samba ]]; then
+#  source 140-install-samba
+#else
+#  echo "missing file: 140-install-samba"
+#  exit 1
+#fi
+
+
 
 #ARCHLINUX U INSTALL {{{
 #1 - WELCOME {{{
@@ -325,14 +348,6 @@ install_basic_setup(){
   package_install "avahi nss-mdns"
   is_package_installed "avahi" && system_ctl enable avahi-daemon
  # pause_function
-  print_title "ALSA - https://wiki.archlinux.org/index.php/Alsa"
-  print_info "The Advanced Linux Sound Architecture (ALSA) is a Linux kernel component intended to replace the original Open Sound System (OSSv3) for providing device drivers for sound cards."
-  package_install "alsa-utils alsa-plugins"
- # pause_function
-  print_title "PULSEAUDIO - https://wiki.archlinux.org/index.php/Pulseaudio"
-  print_info "PulseAudio is the default sound server that serves as a proxy to sound applications using existing kernel sound components like ALSA or OSS"
-  package_install "pulseaudio pulseaudio-alsa"
-  #pause_function
   print_title "NTFS/FAT/exFAT/F2FS - https://wiki.archlinux.org/index.php/File_Systems"
   print_info "A file system (or filesystem) is a means to organize data expected to be retained after a program terminates by providing procedures to store, retrieve and update data, as well as manage the available space on the device(s) which contain it. A file system organizes data in an efficient manner and is tuned to the specific characteristics of the device."
   package_install "ntfs-3g dosfstools exfat-utils f2fs-tools fuse fuse-exfat autofs mtpfs"
@@ -557,15 +572,6 @@ install_video_cards(){
     add_line "export VDPAU_DRIVER=va_gl" "/etc/profile"
   fi
   #pause_function
-}
-#}}}
-#CUPS {{{
-install_cups(){
-  print_title "CUPS - https://wiki.archlinux.org/index.php/Cups"
-  print_info "CUPS is the standards-based, open source printing system developed by Apple Inc. for Mac OS X and other UNIX-like operating systems."
-    package_install "cups cups-filters ghostscript gsfonts"
-    package_install "gutenprint foomatic-db foomatic-db-engine foomatic-db-nonfree foomatic-db-ppds foomatic-db-nonfree-ppds hplip splix cups-pdf foomatic-db-gutenprint-ppds"
-    system_ctl enable org.cups.cupsd.service
 }
 #}}}
 #ADDITIONAL FIRMWARE {{{
@@ -798,58 +804,7 @@ install_office_apps(){
           package_install "goldendict"
 }
 #}}}
-#SYSTEM TOOLS {{{
-install_system_apps(){
-    print_title "SYSTEM TOOLS APPS"
-          package_install "clamav"
-          cp /etc/clamav/clamd.conf.sample /etc/clamav/clamd.conf
-          cp /etc/clamav/freshclam.conf.sample /etc/clamav/freshclam.conf
-          sed -i '/Example/d' /etc/clamav/freshclam.conf
-          sed -i '/Example/d' /etc/clamav/clamd.conf
-          system_ctl enable clamd
-          freshclam
-    	aur_package_install "cockpit storaged linux-user-chroot ostree"
-        aur_package_install "webmin"
-        package_install "docker"
-        add_user_to_group ${username} docker
-        is_package_installed "ufw" && package_remove "ufw"
-        is_package_installed "firewalld" && package_remove "firewalld"
-        package_install "firewalld"
-        system_ctl enable firewalld
-        package_install "gparted"
-        package_install "grsync"
-        aur_package_install "hosts-update"
-        hosts-update
-        package_install "htop"
-        aur_package_install "plex-media-server"
-        system_ctl enable plexmediaserver.service
-        print_title "UFW - https://wiki.archlinux.org/index.php/Ufw"
-        print_info "Ufw stands for Uncomplicated Firewall, and is a program for managing a netfilter firewall. It provides a command line interface and aims to be uncomplicated and easy to use."
-        is_package_installed "firewalld" && package_remove "firewalld"
-        aur_package_install "ufw gufw"
-        system_ctl enable ufw.service
-        aur_package_install "unified-remote-server"
-        system_ctl enable urserver.service
-          #Make sure we are not a VirtualBox Guest
-          VIRTUALBOX_GUEST=`dmidecode --type 1 | grep VirtualBox`
-          if [[ -z ${VIRTUALBOX_GUEST} ]]; then
-            package_install "virtualbox virtualbox-host-dkms virtualbox-guest-iso linux-headers"
-            aur_package_install "virtualbox-ext-oracle"
-            add_user_to_group ${username} vboxusers
-            modprobe vboxdrv vboxnetflt
-          else
-            cecho "${BBlue}[${Reset}${Bold}!${BBlue}]${Reset} VirtualBox was not installed as we are a VirtualBox guest."
-          fi
-        package_install "icoutils wine wine_gecko wine-mono winetricks"
-        package_install "netdata"
-          system_ctl enable netdata.service
-        package_install "nload"
-        package_install "gnome-logs"
-        package_install "qjournalctl"
-        package_install "pacmanlogviewer"
-        package_install "seahorse"
-}
-#}}}
+
 #GRAPHICS {{{
 install_graphics_apps(){
     print_title "GRAPHICS APPS"
@@ -1352,6 +1307,7 @@ automatic_mode
   #Basic Setup
         add_custom_repositories
         install_basic_setup
+        install_sound
         install_zsh
         install_ssh
         install_nfs
