Update 110-install-sound

diff --git a/110-install-sound b/110-install-sound
--- a/110-install-sound
+++ b/110-install-sound
@@ -5,12 +5,12 @@ set -e
 #   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
 #
 ##################################################################################################################
-if [[ -f `pwd`/sharedfuncs ]]; then
-  source sharedfuncs
-else
-  echo "missing file: sharedfuncs"
-  exit 1
-fi
+#if [[ -f `pwd`/sharedfuncs ]]; then
+#  source sharedfuncs
+#else
+#  echo "missing file: sharedfuncs"
+#  exit 1
+#fi
 #SOUND SETUP {{{
 install_sound(){
     print_title "PULSEAUDIO - https://wiki.archlinux.org/index.php/Pulseaudio"
