Update 200-install-system-tools

diff --git a/200-install-system-tools b/200-install-system-tools
--- a/200-install-system-tools
+++ b/200-install-system-tools
@@ -1,10 +1,10 @@
 #!/bin/bash
-if [[ -f `pwd`/sharedfuncs ]]; then
-  source sharedfuncs
-else
-  echo "missing file: sharedfuncs"
-  exit 1
-fi
+#if [[ -f `pwd`/sharedfuncs ]]; then
+#  source sharedfuncs
+#else
+#  echo "missing file: sharedfuncs"
+#  exit 1
+#fi
 
 #SYSTEM TOOLS {{{
 install_system_apps(){
