Update 600-install-Arco

diff --git a/600-install-Arco b/600-install-Arco
--- a/600-install-Arco
+++ b/600-install-Arco
@@ -7,12 +7,12 @@ set -e
 ##################################################################################################################
 
 
-if [[ -f `pwd`/sharedfuncs ]]; then
-  source sharedfuncs
-else
-  echo "missing file: sharedfuncs"
-  exit 1
-fi
+#if [[ -f `pwd`/sharedfuncs ]]; then
+#  source sharedfuncs
+#else
+#  echo "missing file: sharedfuncs"
+#  exit 1
+#fi
 #INSTALL ARCOLINUX {{{
 install_arcolinux(){
     echo "################################################################"
